
services:
  app:
    build: .
    container_name: webmind_be
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    networks:
      - app-network